### ISSUE TITLE
A question about the best random solution

### ISSUE THREAD

**Issue by DWin233** [aliasgharheidaricom/RUN-Beyond-the-Metaphor-An-Efficient-Optimization-Algorithm-Based-on-Runge-Kutta-Method#1]
In line 67, due to the introduction of the temporary array `[A B C]`, the index `ind1` actually came from a 1*3 array, and its value was only 1, 2 or 3. Therefore, in the comparison of line 75, the cost of the current index `i` was always compared with the cost of index 1~3. This did not seem to match the description in the paper.

https://github.com/aliasgharheidaricom/RUN-Beyond-the-Metaphor-An-Efficient-Optimization-Algorithm-Based-on-Runge-Kutta-Method/blob/e4062a8d9ee17356bc4692bbc73fde7a5314b396/RUN.m#L66-L81

**Comment by aliasgharheidaricom** [comment]
thanks, issue solved in code

**Comment by aliasgharheidaricom** [comment]
thanks issue solved
